[build-system]
requires = ["uv_build >= 0.10.0, <0.11.0"]
build-backend = "uv_build"

[project]
name = "circStudio"
version = "1.0.7"
authors = [
    { name="Daniel Marques", email="daniel.marques@gimm.pt" },
    { name="Nuno Morais", email="nuno.morais@nms.unl.pt" },
    { name="Cátia Reis", email="catia.reis@medicina.ulisboa.pt" }
]
description = "A Python toolkit for smoothing, modeling, and analyzing actigraphy time series."
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
keywords = [
    "actigraphy",
    "actimetry",
    "wearables",
    "rhythm analysis",
    "time-series",
    "circadian",
    "ultradian",
    "chronobiology",
    "sleep",
    "cosinor",
    "rest-activity",
    "biological rhythms",
    "functional modeling"
]

license = { file = "LICENSE.md" }
readme = "README.rst"

dependencies = [
    'lmfit>=1.3.4,<2',
    'pandas>=2.3.3,<3',
    'numpy>=2.4.1,<3',
    'scipy>=1.17.0,<2',
    'statsmodels>=0.14.6,<1',
    'plotly>=6.5.2,<7',
    'seaborn>=0.13.2,<1',
    'matplotlib>=3.10.8,<4',
    'pyexcel>=0.7.4,<1',
    'pingouin'
]

[project.urls]
Homepage = "https://github.com/djmarques/circStudio"
Issues = "https://github.com/djmarques/circStudio/issues"

[tool.uv.build-backend]
source-include = ["src/circstudio/data/**"]
